add suport for python virtualenv prompt colorize

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -128,3 +128,67 @@ docker_rmi_tag() {
   tag=${1-none}
   docker images | grep $tag | awk '{print $1 ":" $2}' | xargs docker rmi -f 
 }
+
+####
+# Python Virtual ENV
+####
+# determine git branch name
+function parse_git_branch(){
+  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
+}
+
+# determine mercurial branch name
+function parse_hg_branch(){
+  hg branch 2> /dev/null | awk '{print " (" $1 ")"}'
+}
+
+# Determine the branch/state information for this git repository.
+function set_git_branch() {
+  # Get the name of the branch.
+  branch=$(parse_git_branch)
+  # if not git then maybe mercurial
+  if [ "$branch" == "" ]
+  then
+    branch=$(parse_hg_branch)
+  fi
+
+  # Set the final branch string.
+  BRANCH="${PURPLE}${branch}${COLOR_NONE} "
+}
+
+# Return the prompt symbol to use, colorized based on the return value of the
+# previous command.
+function set_prompt_symbol () {
+  if test $1 -eq 0 ; then
+      PROMPT_SYMBOL="\$"
+  else
+      PROMPT_SYMBOL="${LIGHT_RED}\$${COLOR_NONE}"
+  fi
+}
+
+# Determine active Python virtualenv details.
+function set_virtualenv () {
+  if test -z "$VIRTUAL_ENV" ; then
+      PYTHON_VIRTUALENV=""
+  else
+      PYTHON_VIRTUALENV="${BLUE}[`basename \"$VIRTUAL_ENV\"`]${COLOR_NONE} "
+  fi
+}
+
+# Set the full bash prompt.
+function set_bash_prompt () {
+  # Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
+  # return value of the last command.
+  set_prompt_symbol $?
+
+  # Set the PYTHON_VIRTUALENV variable.
+  set_virtualenv
+
+  # Set the BRANCH variable.
+  set_git_branch
+
+  # Set the bash prompt variable.
+  PS1="
+${PYTHON_VIRTUALENV}${GREEN}\u@\h${COLOR_NONE}:${YELLOW}\w${COLOR_NONE}${BRANCH}
+${PROMPT_SYMBOL} "
+}
